version: '3.8'

services:
  license_bot:
    build: .
    container_name: license_alert_bot
    restart: unless-stopped
    volumes:
      - ./src:/app/src            # Source code
      - ./session:/app/src/.wwebjs_auth  # Session WhatsApp (persistent)
      - ./qr:/app/qr          # QR code
      - ./licenses:/app/licenses  # License files
    environment:
      - TZ=Asia/Jakarta
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
